# Generated by Django 2.0.8 on 2018-10-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_staff'),
        ('membership', '0008_member_sidomo_user_id'),
    ]

    operations = [
    ]
