# Generated by Django 2.0.8 on 2018-09-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0002_article_page_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='membership.Staff', verbose_name='author'),
        ),
    ]
