# Generated by Django 2.0.8 on 2018-10-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0004_auto_20180922_0925'),
        ('cp_articles', '0004_auto_20180927_0454'),
    ]

    operations = [
    ]
