# Generated by Django 2.0.8 on 2018-11-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0009_auto_20181016_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandidentity',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_google',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_keys',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_og_desc',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_og_image',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_og_site_name',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_og_type',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='meta_og_url',
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
