# Generated by Django 2.0.8 on 2018-11-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0010_auto_20181114_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandidentity',
            name='head_scripts',
            field=models.TextField(blank=True),
        ),
    ]
