# Generated by Django 2.0.8 on 2018-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0013_remove_brandidentity_meta_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandidentity',
            name='horizontal_banner_scripts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='infeed_ads_scripts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='sidebar_scripts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='vertical_banner_scripts',
            field=models.TextField(blank=True),
        ),
    ]
